baseurl = "http://example.org"
title = "LSESU CSS"
theme = "dimension"
languageCode = "en-us"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = "The official website for the first ever LSE hackathon on computational social science April 21-22, 2018"
  logo = "fa-code"
  copyright = "2017 LSESU CSS Society"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"