baseurl = "https://www.cssatlse.com"
title = "LSESU CSS"
theme = "dimension"
languageCode = "en-us"
enableRobotsTXT = true
disableKinds=["RSS"]
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  description = "The official website for the first ever LSE hackathon on computational social science April 17-19, 2018"
  #logoimage = "/images/icon.png"
  logo = "fa-code"
  copyright = "2018 LSESU CSS Society"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/cssatlse"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/cssatlse/"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/company/cssatlse/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/cssatlse"